'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {promptFor,validationProblems,expectedScore}=require('./pilot-g4-real');
const input={g4:{g4_conjuntos_pares_total:1,g4_conjuntos_pares:[{conjunto:'S1',n:3,miembros:[{id:1},{id:2},{id:3}]}],g4_banner_candidatos:[{id:10},{id:11}],g4_cromo_candidatos:[{id:20}]},geometria_nodos:[{id:11,parentId:10}]};
const run={model_id:'synthetic-model-1',runtime:'synthetic-test',repetition:1,prompt_hash:'a'.repeat(64),captured_at:'2026-10-07T12:00:00Z',decoding:{declarado:'synthetic'},capture_sha256:{wireframe:'b'.repeat(64),screenshot:'c'.repeat(64)},measurements_version:'1.0.6',protocol_version:'0.1.0'};
function raw(){return {group_id:'g4',group_name:'Saliencia visual',laws_subsumed:['Von Restorff','Atención selectiva'],channel:'screenshot',not_applicable:false,na_reason:null,score:4,trigger:'ninguna',evidence_insufficient:false,
 measurements:{sets:1,g4_conjuntos_pares_total:1,I_principal:1,I_total:1,P:true,Bn:0,Cn:0,main_set_id:'S1',jerarquia_entre_dos:null,ancla_definida:true,motivo_abstencion:null,Bn_ids:[],Cn_ids:[],channels_of_isolation:2,canales_aislamiento:['color','peso'],lectura_screenshot:['P'],juicios_conjuntos:[{conjunto:'S1',equivalentes:true,aislados_ids:[1]}]},findings:[],recommendations:[]};}
const check=(r,s=input)=>validationProblems(r,s,run,new Set([1,2,3,10,11,20]));
test('acepta atribución sin modificar respuesta',()=>{const r=raw(),before=JSON.stringify(r);assert.deepEqual(check(r),[]);assert.equal(JSON.stringify(r),before);});
test('rechaza sustituir cifras o miembros',()=>{const r=raw();r.measurements.sets=9;r.measurements.juicios_conjuntos[0].aislados_ids=[99];assert.ok(check(r).length>=2);});
test('rechaza selección principal inventada',()=>{const r=raw();r.measurements.main_set_id='S2';assert.ok(check(r).some(e=>e.includes('principal')));});
test('rechaza puntaje incompatible con sus juicios',()=>{const r=raw();r.score=0;assert.ok(check(r).some(e=>e.includes('anclas')));});
test('los casos sin ancla no se convierten en cero',()=>{const r=raw();Object.assign(r.measurements,{I_principal:0,I_total:0,P:null,channels_of_isolation:0,canales_aislamiento:[],lectura_screenshot:[],ancla_definida:false,motivo_abstencion:'I=0 sin Bn',juicios_conjuntos:[{conjunto:'S1',equivalentes:true,aislados_ids:[]}]});r.score=null;r.trigger=null;r.evidence_insufficient=true;assert.deepEqual(check(r),[]);r.score=0;assert.ok(check(r).some(e=>e.includes('abstención')));});
test('NA se distingue de abstención y exige cero candidatos',()=>{const r=raw();r.not_applicable=true;r.score=null;r.trigger=null;r.na_reason='Sin pares';r.measurements.ancla_definida=false;assert.ok(check(r).some(e=>e.includes('no aplicabilidad')));});
test('rechaza doble conteo de banner por ancestro e hijo',()=>{const r=raw();r.measurements.Bn_ids=[10,11];r.measurements.Bn=2;r.score=1;r.trigger='Bn';r.recommendations=['Fixture'];assert.ok(check(r).some(e=>e.includes('ancestro')));});
test('canales independientes y texto deben quedar declarados',()=>{const r=raw();r.measurements.canales_aislamiento=['color','color'];r.measurements.lectura_screenshot=[];const p=check(r);assert.ok(p.some(e=>e.includes('canales')));assert.ok(p.some(e=>e.includes('lectura')));});
test('exige declarar cajas parciales o raíces virtuales',()=>{const s=structuredClone(input);s.g4.g4_conjuntos_pares[0].parcial=true;assert.ok(check(raw(),s).some(e=>e.includes('estructural')));});
test('las anclas conservadas tienen prioridad y huecos explícitos',()=>{const m=raw().measurements;assert.equal(expectedScore({...m,I_principal:0,Bn:1}),0);assert.equal(expectedScore({...m,I_principal:3,Bn:0}),1);assert.equal(expectedScore({...m,I_principal:2,jerarquia_entre_dos:false}),2);assert.equal(expectedScore({...m,P:false}),2);assert.equal(expectedScore({...m,channels_of_isolation:1}),3);assert.equal(expectedScore(m),4);assert.equal(expectedScore({...m,I_principal:0}),null);assert.equal(expectedScore({...m,I_principal:2,jerarquia_entre_dos:true}),null);assert.equal(expectedScore({...m,Cn:1}),null);});
test('prompt idéntico y canal screenshot sin wireframe adjunto',()=>{assert.equal(promptFor(input,'rubric','scale'),promptFor(input,'rubric','scale'));assert.ok(promptFor(input,'rubric','scale').includes('No se suministra wireframe'));});
test('acepta NA con cero candidatos y sin inventar juicios',()=>{const r=raw();Object.assign(r,{not_applicable:true,score:null,trigger:null,na_reason:'Cero candidatos'});Object.assign(r.measurements,{sets:0,g4_conjuntos_pares_total:0,I_principal:null,I_total:0,P:null,main_set_id:null,ancla_definida:false,channels_of_isolation:0,canales_aislamiento:[],lectura_screenshot:[],juicios_conjuntos:[]});const s=structuredClone(input);s.g4.g4_conjuntos_pares_total=0;s.g4.g4_conjuntos_pares=[];assert.deepEqual(check(r,s),[]);});
test('rechaza trigger sin la condición declarada',()=>{const r=raw();r.trigger='Cn';assert.ok(check(r).some(e=>e.includes('trigger')));});
