'use strict';
const fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto');
const {test}=require('node:test'),assert=require('node:assert/strict'),{archiveTechnical}=require('./resume-g4-technical');
function fixture(){const d=fs.mkdtempSync(path.join(os.tmpdir(),'g4-retry-test-'));for(const f of ['trazas','respuestas','resultados'])fs.mkdirSync(path.join(d,f));const trace=JSON.stringify({type:'turn.failed',error:{message:'synthetic'}})+'\n';fs.writeFileSync(path.join(d,'trazas','T01-r1.jsonl'),trace);const proof={id:'T01-r1',status:'error_tecnico',exit:{code:1},usage:null,thread_id:'synthetic',errors:['synthetic'],trace_sha256:crypto.createHash('sha256').update(trace).digest('hex')};fs.writeFileSync(path.join(d,'trazas','T01-r1.json'),JSON.stringify(proof));return d;}
function clean(d){fs.rmSync(d,{recursive:true,force:true});}
test('archiva fallo sin respuesta y conserva hashes y atribución',()=>{const d=fixture();try{const before=fs.readFileSync(path.join(d,'trazas','T01-r1.json')),r=archiveTechnical(d);assert.equal(r.length,1);assert.deepEqual(fs.readFileSync(path.join(d,r[0].archivo,'T01-r1.json')),before);assert.ok(!fs.existsSync(path.join(d,'trazas','T01-r1.json')));assert.ok(fs.existsSync(path.join(d,'REANUDACION-1.json')));}finally{clean(d);}});
test('no reintenta una respuesta presente',()=>{const d=fixture();try{fs.writeFileSync(path.join(d,'respuestas','T01-r1.json'),'{}');assert.throws(()=>archiveTechnical(d));assert.ok(fs.existsSync(path.join(d,'trazas','T01-r1.json')));}finally{clean(d);}});
test('rechaza traza alterada',()=>{const d=fixture();try{fs.appendFileSync(path.join(d,'trazas','T01-r1.jsonl'),'{}\n');assert.throws(()=>archiveTechnical(d));}finally{clean(d);}});
test('deja puntajes, inválidos y abstenciones sin repetir',()=>{for(const status of ['valido','abstencion','invalido']){const d=fixture();try{const p=path.join(d,'trazas','T01-r1.json'),v=JSON.parse(fs.readFileSync(p));v.status=status;fs.writeFileSync(p,JSON.stringify(v));assert.equal(archiveTechnical(d).length,0);assert.ok(fs.existsSync(p));}finally{clean(d);}}});
test('rechaza un fallo que también contiene un juicio emitido',()=>{const d=fixture();try{const p=path.join(d,'trazas','T01-r1.json'),trace=JSON.stringify({type:'item.completed',item:{type:'agent_message',text:'{}'}})+'\n';fs.writeFileSync(path.join(d,'trazas','T01-r1.jsonl'),trace);const v=JSON.parse(fs.readFileSync(p));v.trace_sha256=crypto.createHash('sha256').update(trace).digest('hex');fs.writeFileSync(p,JSON.stringify(v));assert.throws(()=>archiveTechnical(d));}finally{clean(d);}});
