'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {PNG}=require('pngjs');const {medirG4,rasgosDe,median}=require('./g4-visual');
function ctx(nodes){const png=new PNG({width:100,height:100});png.data.fill(255);return {conInk:nodes,png,fondo:[248,248,248],viewport:{width:100,height:100},porId:new Map(nodes.map(n=>[n.id,n])),inventarioAccionables:{objetivosG2:[]},ancestros:()=>[]};}
const node=(id,tag='A',parentId=10,b={x:id*10,y:10,w:8,h:8})=>({id,nodeName:tag,parentId,ink:b});
test('incluye pares de dos elementos y preserva todos los miembros',()=>{const g=medirG4(ctx([node(1),node(2)]));assert.equal(g.g4_conjuntos_pares_total,1);assert.equal(g.g4_conjuntos_pares[0].n,2);assert.equal(g.g4_conjuntos_pares[0].miembros.length,2);});
test('no convierte fragmentos ni pseudoelementos en conjuntos',()=>{assert.equal(medirG4(ctx([node(1,'#text'),node(2,'#text'),node(3,'::before'),node(4,'::before')])).g4_conjuntos_pares_total,0);});
test('excluye regiones hijas de BODY, conservando el límite raíz virtual',()=>{const g=medirG4(ctx([node(10,'BODY',null),node(1,'DIV'),node(2,'DIV'),node(3,'A',null),node(4,'A',null)]));assert.equal(g.g4_conjuntos_pares_total,1);assert.equal(g.g4_conjuntos_pares[0].padre_raiz_virtual,true);});
test('no trunca a ocho conjuntos ni a veinte miembros',()=>{const nodes=Array.from({length:11},(_,i)=>[node(i*2+1,'A',i+100,{x:1,y:1,w:5,h:5}),node(i*2+2,'A',i+100,{x:10,y:1,w:5,h:5})]).flat();assert.equal(medirG4(ctx(nodes)).g4_conjuntos_pares_total,11);const more=Array.from({length:25},(_,i)=>node(i+1,'LI',100,{x:1,y:1,w:5,h:5}));assert.equal(medirG4(ctx(more)).g4_conjuntos_pares[0].miembros.length,25);});
test('usa la mediana convencional para conjuntos pares',()=>{assert.equal(median([10,30]),20);assert.equal(median([4,2,8,6]),5);});
test('mide solo píxeles visibles y declara cajas parciales',()=>{const c=ctx([node(1,'A',10,{x:-5,y:0,w:10,h:10}),node(2,'A',10,{x:10,y:0,w:10,h:10})]);const r=rasgosDe(c.png,c.fondo,c.conInk[0].ink);assert.equal(r.pixeles_muestreados,50);assert.equal(r.area,100);assert.equal(r.area_visible,50);assert.equal(medirG4(c).g4_conjuntos_pares[0].parcial,true);});
test('el proxy RGB no se interpreta como contraste de legibilidad',()=>{const c=ctx([]),r=rasgosDe(c.png,[255,255,255],{x:0,y:0,w:10,h:10});assert.equal(r.contraste_con_fondo,0);assert.equal(r.fraccion_tinta,0);});
test('la franja inferior no se marca como banner superior; sin truncación',()=>{const c=ctx([]);c.viewport={width:1000,height:900};c.png=new PNG({width:1000,height:900});c.png.data.fill(255);c.conInk=[node(1,'DIV',10,{x:0,y:600,w:900,h:100}),...Array.from({length:13},(_,i)=>node(i+2,'DIV',10,{x:0,y:10,w:900,h:100}))];c.porId=new Map(c.conInk.map(n=>[n.id,n]));const g=medirG4(c);assert.equal(g.g4_banner_candidatos.length,13);assert.ok(!g.g4_banner_candidatos.some(n=>n.id===1));});
test('contiene_accionables usa pertenencia retenida, no simple solapamiento',()=>{const c=ctx([node(1,'DIV',10,{x:0,y:0,w:900,h:100})]);c.viewport={width:1000,height:900};c.png=new PNG({width:1000,height:900});c.png.data.fill(255);const a=node(2);c.inventarioAccionables.objetivosG2=[a];assert.equal(medirG4(c).g4_banner_candidatos[0].contiene_accionables,0);c.ancestros=()=>c.conInk;assert.equal(medirG4(c).g4_banner_candidatos[0].contiene_accionables,1);});
